<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
if($_SERVER['REQUEST_METHOD']!=='POST')respond(405,'Method not allowed.');requireCsrf();if(!empty($_POST['website']))respond(200,'Thanks.',true);
$last=(int)($_SESSION['last_auth_attempt']??0);if($last&&time()-$last<2)respond(429,'Please wait a moment and try again.');$_SESSION['last_auth_attempt']=time();
$action=(string)($_POST['action']??'');$password=(string)($_POST['password']??'');$id=0;
if($action==='register'){$email=strtolower(trim((string)($_POST['email']??'')));if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>120)respond(422,'Enter a valid email address.');$name=trim((string)($_POST['name']??''));$phone=trim((string)($_POST['phone']??''));if(mb_strlen($name)<2||mb_strlen($name)>80)respond(422,'Enter your full name.');if(strlen(preg_replace('/\D+/','',$phone)??'')<7||strlen($phone)>25)respond(422,'Enter a valid phone number.');if(strlen($password)<8||strlen($password)>128)respond(422,'Use a password with at least 8 characters.');if(($_POST['consent']??'')!=='yes')respond(422,'Please accept the contact and privacy terms.');try{$s=db()->prepare('INSERT INTO users(created_at,name,email,phone,password_hash) VALUES(?,?,?,?,?)');$s->execute([gmdate('c'),$name,$email,$phone,password_hash($password,PASSWORD_DEFAULT)]);$id=(int)db()->lastInsertId();}catch(PDOException $e){if(str_contains($e->getMessage(),'UNIQUE'))respond(409,'An account with this email already exists. Sign in instead.');error_log($e->getMessage());respond(500,'We could not create the account.');}}
elseif($action==='login'){$identifier=trim((string)($_POST['identifier']??$_POST['email']??''));if($identifier===''||strlen($identifier)>120)respond(422,'Enter your email or mobile number.');if(filter_var($identifier,FILTER_VALIDATE_EMAIL)){$s=db()->prepare('SELECT id,password_hash FROM users WHERE email=?');$s->execute([strtolower($identifier)]);}else{$digits=preg_replace('/\D+/','',$identifier);if($digits===null||strlen($digits)<7)respond(422,'Enter a valid email or mobile number.');$s=db()->prepare("SELECT id,password_hash FROM users WHERE REPLACE(REPLACE(REPLACE(REPLACE(phone,'-',''),' ',''),'(',''),')','')=REPLACE(?, '+', '')");$s->execute([$digits]);}$row=$s->fetch(PDO::FETCH_ASSOC);if(!$row||!password_verify($password,$row['password_hash']))respond(401,'Email/mobile or password is incorrect.');$id=(int)$row['id'];db()->prepare('UPDATE users SET last_login_at=? WHERE id=?')->execute([gmdate('c'),$id]);if(password_needs_rehash($row['password_hash'],PASSWORD_DEFAULT))db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),$id]);}
else respond(400,'Unknown account action.');
session_regenerate_id(true);$_SESSION['user_id']=$id;$_SESSION['csrf']=bin2hex(random_bytes(32));respond(200,'Signed in.',true,['user'=>currentUser(),'csrf'=>$_SESSION['csrf']]);
